### ISSUE TITLE
Ideas, reviews, etc

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/pycon_2015#1]
@birdage I just wrote some quick slides while waiting for my flight.  Feel free to make any changes you think it is necessary.

I will add something more about our participation in the project in the end, but right now it is just "how I met folium."

**Comment by birdage** [comment]
@ocefpaf sounds good, i see the notebook, but i dont see a ppt

**Comment by ocefpaf** [comment]
I will use the notebook in slide mode or I will convert to landslides via
the notebook markdown. Not sure yet, but no ppt ;-)
Em 09/04/2015 10:25, "Andrew Bird" <notifications@github.com> escreveu:

**Comment by birdage** [comment]
@ocefpaf looking good! looking forward to hearing how it goes, the next year for folium is going to be good! Its a great open tool for the open source community!

**Comment by ocefpaf** [comment]
I decided to go with Markdown+landslide.  Here is the rendered version:

http://ocefpaf.github.io/pycon_2015/slides.html

If you want to change/add anything just edit the `slides.md` file and I will compile it again here.

Thanks @birdage!

**Comment by birdage** [comment]
you might wanna mentioned that we already have used it for open projects and continue to do so!

**Comment by ocefpaf** [comment]
It is not in the slide. But I will try to open the SECOORA website. Do you
have something I can show?
Em 10/04/2015 10:32, "Andrew Bird" <notifications@github.com> escreveu:

**Comment by birdage** [comment]
this is a notebook i did showing a hurricane path and USGS rapid deployment gages, shows marker cluster and some other good things. suggest clicking on the "42"

http://nbviewer.ipython.org/github/ioos/system-test/blob/master/Theme_2_Extreme_Events/Scenario_2D/USGS_Gauges/Rapid_Deploy_Gauges.ipynb

**Comment by ocefpaf** [comment]
Nice! I will add that one.
Em 10/04/2015 15:37, "Andrew Bird" <notifications@github.com> escreveu:
